AllCops:
  Exclude:
    - 'bin/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/LineLength:
  Max: 120

Style/CaseIndentation:
  IndentWhenRelativeTo: 'case'
  IndentOneStep: true

Style/IndentHash:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FirstParameterIndentation:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: 'indented'

Style/RedundantReturn:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
